version: "3.9"

services:
  minio:
    image: bitnami/minio:latest
    profiles: ["backend"]
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=qwerty123
    volumes:
      - minio_data:/data'

volumes:
  minio_data:
