AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Converts a PDF file from S3 to an HTML document

# Globals:
#   Function:
#     # Need to explicitly define the environment variables
#     Environment:
#       Variables:
#         AWS_ACCESS_KEY_ID:
#         AWS_SECRET_ACCESS_KEY:
#         AWS_REGION:
#         AWS_S3_ENDPOINT:

Resources:
  Pdf2HtmlFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 180
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: ./pdf2html-lambda/Dockerfile

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt Pdf2HtmlFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt Pdf2HtmlFunction.Arn
